# Generated by Django 5.1.2 on 2024-10-17 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                ("customer_name", models.CharField(max_length=100)),
                ("total", models.FloatField()),
                ("datetime", models.CharField(max_length=45)),
            ],
            options={
                "db_table": "orders",
            },
        ),
        migrations.CreateModel(
            name="UOM",
            fields=[
                ("uom_id", models.AutoField(primary_key=True, serialize=False)),
                ("uom_name", models.CharField(max_length=45)),
            ],
            options={
                "db_table": "uom",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("price_per_unit", models.FloatField()),
                (
                    "uom_id",
                    models.ForeignKey(
                        db_column="uom_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="products",
                        to="orders.uom",
                    ),
                ),
            ],
            options={
                "db_table": "products",
            },
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField()),
                ("total_price", models.FloatField()),
                (
                    "order_id",
                    models.ForeignKey(
                        db_column="order_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="order_details",
                        to="orders.order",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="order_details",
                        to="orders.product",
                    ),
                ),
            ],
            options={
                "db_table": "order_details",
                "unique_together": {("order_id", "product_id")},
            },
        ),
    ]
