# Generated by Django 5.1.2 on 2024-10-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_orderdetails_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="datetime",
            field=models.DateTimeField(),
        ),
    ]
